name: sd-api-server
channels:
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - cudatoolkit=11.7
  - pytorch-cuda
  - pytorch
  - torchvision
  - numpy
  - pip:
      - requests
      - diffusers
      - transformers
      - Pillow
      - Flask
      - accelerate
      - ftfy
